sudo: required

services:
- docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

language: bash

script:
- docker --version
- docker build -t thenatureofsoftware/helloworld:latest .
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push thenatureofsoftware/helloworld:latest
  fi
